version: '3.8'

services:
    dev:
        build:
            context: .
            dockerfile: ./dev.dockerfile
        ports:
            - '3000:3000'
    build:
        build:
            context: .
            dockerfile: ./build.dockerfile
        volumes:
            - ./build:/usr/src/app/build

