version: '3.8'

services:
    dev:
        container_name: dev
        build:
            dockerfile: ./dev.dockerfile
            target: dev
        ports:
            - '3000:3000'
        volumes:
            - ./:/usr/src/app

